routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\ProductController;
use \App\Http\Controllers\BoxController;
use \App\Http\Controllers\SupplierController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::permanentRedirect('/', '/products');

Route::get('products/jsonData', [ProductController::class, 'jsonData'])->name('products.jsonData');
Route::resource('products', ProductController::class);
Route::get('boxes', [BoxController::class, 'index'])->name('boxes.index');
Route::post('boxes', [BoxController::class, 'store'])->name('boxes.store');
Route::get('boxes/create', [BoxController::class, 'create'])->name('boxes.create');
Route::get('suppliers/jsonData', [SupplierController::class, 'jsonData'])->name('suppliers.jsonData');
Route::get('suppliers', [SupplierController::class, 'index'])->name('suppliers.index');

app/Models/Box.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class Box extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'discount',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_boxes')->using(ProductBox::class)->withTimestamps();
    }

    /**
     * @param $value
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d.m.Y H:i:s');
    }

    /**
     * @param $data
     * @return bool
     */
    public static function createBoxWithPivot($data)
    {
        DB::beginTransaction();
        try {
            self::create([
                'name' => $data['name'],
                'discount' => $data['discount']
            ])->products()->attach($data['products']);

            DB::commit();
            return true;
        } catch (\Exception $exception){
            Log::error($exception);
            DB::rollBack();
            return false;
        }
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'in_storage',
        'price',
        'photo',
        'supplier_id',
    ];

    protected $casts = [
        'in_storage' => 'boolean'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function boxes()
    {
        return $this->belongsToMany(Box::class)->using(ProductBox::class)->withTimestamps();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    /**
     * @param $value
     * @return string
     */
    public function getUpdatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d.m.Y H:i:s');
    }

    public function scopeFilters(Builder $query)
    {
        if (request()->has('search') && !empty(request()->get('search'))) {
            $query->where(function (Builder $q) {
                $q->where('id', request()->get('search'))
                    ->orWhere('name', 'like', '%' . request()->get('search') . '%')
                    ->orWhereHas('supplier', function (Builder $qe) {
                        $qe->where('name', 'like', '%' . request()->get('search') . '%');
                    });
            });
        }
        if (request()->has('in_storage') && request()->get('in_storage') == 1){
            $query->where('in_storage', true);
        }
        if (request()->has('order_by') && !empty(request()->get('order_by'))){
            $order = explode(',',request()->get('order_by'));
            $query->orderBy($order[0], $order[1] ?? 'asc');
        }
        return $query;
    }

    /**
     * @param $data
     * @return bool
     */
    public static function createProductWithFile($data)
    {
        DB::beginTransaction();
        try {
            self::create([
                'name' => $data['name'],
                'in_storage' => $data['in_storage'] ?? 0,
                'price' => $data['price'],
                'photo' => !empty($data['photo']) ? Storage::disk('public')->putFile('products', $data['photo']) : null,
                'supplier_id' => $data['supplier_id']
            ]);

            DB::commit();
            return true;
        } catch (\Exception $exception) {
            Log::error($exception);
            DB::rollBack();
            return false;
        }
    }

    /**
     * @param $data
     * @return bool
     */
    public function updateProductWithFile($data)
    {
        DB::beginTransaction();
        try {
            $updatingData = [
                'name' => $data['name'],
                'in_storage' => $data['in_storage'] ?? 0,
                'price' => $data['price'],
                'supplier_id' => $data['supplier_id']
            ];
            if (!empty($data['photo'])) {
                $updatingData['photo'] = Storage::disk('public')->putFile('products', $data['photo']);
            }
            $this->update($updatingData);

            DB::commit();
            return true;
        } catch (\Exception $exception) {
            Log::error($exception);
            DB::rollBack();
            return false;
        }
    }

    public function removeProductWithFile()
    {
        DB::beginTransaction();
        try {
            $hasFile = false;
            if (!empty($this->photo)) {
                $hasFile = true;
            }
            $this->delete();
            if ($hasFile) {
                Storage::disk('public')->delete($this->photo);
            }
            DB::commit();
            return true;
        } catch (\Exception $exception) {
            Log::error($exception);
            DB::rollBack();
            return false;
        }
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductStoreRequest;
use App\Http\Resources\ProductJsonResource;
use App\Models\Box;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        return view('product.index', ['products' => Product::filters()->paginate($this->perPage)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create', ['suppliers' => Supplier::all()->pluck('name', 'id')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductStoreRequest $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(ProductStoreRequest $request)
    {
        if(!Product::createProductWithFile($request->validated())){
            return back()->with('error', 'Something went wrong. Please try again.');
        }

        return redirect(route('products.index'))->with('success', 'Product was created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(Product $product)
    {
        $boxes = Box::whereHas('products', function(Builder $query) use ($product){
            return $query->where('product_id', $product->id);
        })->paginate($this->perPage);
        return view('product.show', ['product' => $product, 'boxes' => $boxes]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductStoreRequest $request
     * @param Product $product
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(ProductStoreRequest $request, Product $product)
    {
        if(!$product->updateProductWithFile($request->validated())){
            return back()->with('error', 'Something went wrong. Please try again.');
        }

        return back()->with('success', 'Product was updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Product $product)
    {
        if(!$product->removeProductWithFile()){
            return back()->with('error', 'Something went wrong. Please try again.');
        }

        return redirect(route('products.index'))->with('success', 'Product was removed successfully.');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function jsonData(Request $request)
    {
        if ($request->exists('search')) {
            $collection = Product::where('name', 'LIKE', '%' . $request->get('search') . '%')->get(['id', 'name']);
        } else {
            $collection = Product::all(['id', 'name']);
        }
        return ProductJsonResource::collection($collection);
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
    @if($errors->any())
        <ul style="color:#ff0000">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    <form class="space-y-4 text-gray-700" method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="name">Name</label>
                <input name="name" required
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="text" id="name" value="{{ old('name') }}"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="photo">Photo</label>
                <input name="photo"
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="file" id="photo" accept="image/x-png,image/gif,image/jpeg"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="in_storage">In storage</label>
                <input name="in_storage"
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="checkbox" id="in_storage" value="1"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="price">Price</label>
                <input name="price"
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="number" step="any" required id="price" value="{{ old('price') }}"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-80">
                <label class="block mb-1" for="supplier_id">Supplier</label>
                <select id="supplier_id" class="select2" required name="supplier_id">
                </select>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <button type="submit"
                        class="inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">
                    Create
                </button>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function () {
            $('.select2').select2({
                width: '100%',
                ajax: {
                    method: 'get',
                    url: '{{ route('suppliers.jsonData') }}',
                    data: function (params) {
                        var query = {
                            search: params.term
                        }
                        // Query parameters will be ?search=[term]&type=public
                        return query;
                    },
                    processResults: function (data, params) {
                        console.log(data.data);
                        return {
                            results: data.data
                        };
                    }
                }
            });
        });
    </script>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    @if($errors->any())
        <ul style="color:#ff0000">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    <form class="space-y-4 text-gray-700" method="post" action="{{ route('products.update', ['product' => $product->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="name">Name</label>
                <input name="name" required
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="text" id="name" value="{{ $product->name }}"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            {!! !empty($product->photo) ? '<div class="w-full"><img class="product_image" src="'.Storage::url($product->photo).'" /></div>' : '' !!}
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="photo">Photo</label>
                <input name="photo"
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="file" id="photo" accept="image/x-png,image/gif,image/jpeg"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="in_storage">In storage</label>
                <input name="in_storage"
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="checkbox" id="in_storage" {{ $product->in_storage ? 'checked' : '' }} value="1"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <label class="block mb-1" for="price">Price</label>
                <input name="price"
                       class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                       type="number" step="any" required id="price" value="{{ $product->price }}"/>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-80">
                <label class="block mb-1" for="supplier_id">Supplier</label>
                <select id="supplier_id" class="select2" required name="supplier_id">
                    <option value="{{ $product->supplier_id }}">{{ $product->supplier->name }}</option>
                </select>
            </div>
        </div>
        <div class="flex flex-wrap">
            <div class="w-[calc(100%+1rem)]">
                <button type="submit"
                        class="inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">
                    Update
                </button>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function () {
            $('.select2').select2({
                width: '100%',
                ajax: {
                    method: 'get',
                    url: '{{ route('suppliers.jsonData') }}',
                    data: function (params) {
                        var query = {
                            search: params.term
                        }
                        // Query parameters will be ?search=[term]&type=public
                        return query;
                    },
                    processResults: function (data, params) {
                        console.log(data.data);
                        return {
                            results: data.data
                        };
                    }
                }
            });
        });
    </script>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <a class="inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800"
       href="{{ route('products.create') }}">Create new Product</a>
    <form class="flex items-end" method="get" action="{{ route('products.index') }}">
        <select id="order_by"
                class="mb-1 mr-2 inline-flex h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                name="order_by">
            <option value="">Order by ID ASC</option>
            <option {{ request('order_by') == 'id,desc' ? 'selected' : '' }} value="id,desc">Order by ID DESC</option>
            <option {{ request('order_by') == 'updated_at' ? 'selected' : '' }} value="updated_at">Order by Updated at ASC</option>
            <option {{ request('order_by') == 'updated_at,desc' ? 'selected' : '' }} value="updated_at,desc">Order by Updated at DESC</option>
        </select>
        <input name="search"
               class="mb-1 inline-flex h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
               type="text" placeholder="Search by ID, Name or Supplier" id="name" value="{{ request('search') }}"/>
        <div class="ml-3">
            <label class="mb-1 mr-2" for="in_storage">In storage</label>
            <input name="in_storage"
                   class="w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
                   type="checkbox" id="in_storage" {{ request('in_storage') ? 'checked' : '' }} value="1"/>
        </div>
        <button
            class="inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800"
            type="submit">Use filters
        </button>
    </form>
    <div class="bg-white overflow-auto">
        <table class="min-w-full bg-white">
            <thead class="bg-gray-800 text-white">
            <tr>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">ID</th>
                <th class="text-left max-w-300 py-3 px-4 uppercase font-semibold text-sm">Photo</th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">In storage</th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Price</th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Supplier
                </td>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Updated at
                </td>
            </tr>
            </thead>
            <tbody class="text-gray-700">
            @foreach($products as $key => $product)
                <tr @if($key%2 == 0) class="bg-gray-200" @endif>
                    <td class="text-left py-3 px-4">{{ $product->id }}</td>
                    <td class="text-left max-w-300 py-3 px-4">{!! !empty($product->photo) ? '<img class="product_image" src="'.Storage::url($product->photo).'" />' : '' !!}</td>
                    <td class="text-left py-3 px-4"><a
                            href="{{ route('products.show', ['product' => $product->id]) }}">{{ $product->name }}</a>
                    </td>
                    <td class="text-left py-3 px-4">{{ $product->in_storage ? 'yes' : 'no' }}</td>
                    <td class="text-left py-3 px-4">{{ $product->price }}</td>
                    <td class="text-left py-3 px-4">{{ $product->supplier->name }}</td>
                    <td class="text-left py-3 px-4">{{ $product->updated_at }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {{ $products->appends(request()->toArray())->links() }}
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex items-center justify-between">
        <a class="inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800"
           href="{{ route('products.edit', ['product' => $product->id]) }}">Edit Product</a>
        <form action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
            @csrf
            @method('DELETE')
            <button class="inline-flex items-center h-8 px-4 m-2 text-sm text-red-100 duration-150 bg-red-700 rounded-lg focus:shadow-outline hover:bg-red-800" type="submit">Delete</button>
        </form>
    </div>
    <div class="flex items-start justify-between">
        <div style="width: 48%">
            {!! !empty($product->photo) ? '<div class="mt-6 mb-6 text-2xl"><div><strong>Photo:</strong></div><img src="'.Storage::url($product->photo).'" /></div>' : '' !!}
            <div class="flex items-center mt-6 mb-6 text-2xl"><strong class="mr-2">Name:</strong> {{ $product->name }}</div>
            <div class="flex items-center mt-6 mb-6 text-2xl"><strong class="mr-2">In storage:</strong> {{ $product->in_storage ? 'yes' : 'no' }}</div>
            <div class="flex items-center mt-6 mb-6 text-2xl"><strong class="mr-2">Price:</strong> {{ $product->price }}</div>
            <div class="flex items-center mt-6 mb-6 text-2xl"><strong class="mr-2">Supplier:</strong> {{ $product->supplier->name }}</div>
            <div class="flex items-center mt-6 mb-6 text-2xl"><strong class="mr-2">Updated at:</strong> {{ $product->updated_at }}</div>
        </div>
        <div style="width: 48%">
            <div class="flex items-center mt-6 mb-6 text-2xl"><strong class="mr-2">In Boxes:</strong></div>
            <table class="min-w-full bg-white">
                <thead class="bg-gray-800 text-white">
                <tr>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">ID</th>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Discount</th>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Number of Products</th>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Created at
                    </td>
                </tr>
                </thead>
                <tbody class="text-gray-700">
                @foreach($boxes as $key => $box)
                    <tr @if($key%2 == 0) class="bg-gray-200" @endif>
                        <td class="text-left py-3 px-4">{{ $box->id }}</td>
                        <td class="text-left py-3 px-4">{{ $box->name }}</td>
                        <td class="text-left py-3 px-4">{{ $box->discount }}</td>
                        <td class="text-left py-3 px-4">{{ $box->products()->count() }}</td>
                        <td class="text-left py-3 px-4">{{ $box->created_at }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $boxes->links() }}
        </div>
    </div>
@endsection